name: Production

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: true
                fetch-depth: 0
            - name: Setup PDM
              uses: pdm-project/setup-pdm@v4
            - name: Install dependencies
              run: pdm install
            - name: Build
              run: pdm run python generate.py
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v4
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./dist
                cname: join.hol0.dev